language: python
sudo: false
cache: pip

python:
  - "3.5"

services:
  - mongodb

before_istall:
  - pip install flake8
  - flake8

install:
  - pip install -r requirements.txt

script:
  - python tests.py

before_script:
  - "mongo abell --eval 'add_user('abell', '123456', roles=[{'role': 'readWrite', 'db': 'abell'}]);'"
